### ISSUE TITLE
Conversion of Geometry from One format to Other

### ISSUE THREAD

**Issue by amitk189** [DotSpatial/DotSpatial#1010]
Hello,

I am doing a application where am in need to convert geometry from one format to other for example

DotSpatial.Topology.Point' to type 'GeoAPI.Geometries.IGeometry' and viceversa, but when ever i do so the exception pops up as  shown below

Unable to cast object of type 'DotSpatial.Topology.Point' to type 'GeoAPI.Geometries.IGeometry'.

Please suggest me a way to convert from one format to other.

Regards,
Amit

**Comment by jany-tenaj** [comment]
This sounds as if you're working with DotSpatial 1.9 and GeoAPI from NetTopologySuite. So check out the [converter](https://github.com/NetTopologySuite/NetTopologySuite/tree/master/NetTopologySuite.Converter/NetTopologySuite.Converter.DotSpatial) from the NetTopologySuite page. 

Not sure what you need the GeoAPI for but maybe consider using DotSpatial 2.0. It contains the GeoAPI and no longer uses DotSpatial.Topology.

If this doesn't help post the code you're using so we can understand what your problem is.

**Comment by amitnkukanur** [comment]
ok
