### ISSUE TITLE
Animation of raster layers

### ISSUE THREAD

**Issue by olejniczak** [DotSpatial/DotSpatial#1045]
### Feature description

I want to create animation (movie) of raster images. I have tried with a simple example:
```
List<IRaster> rasters = new List<IRaster>();
foreach (var file in Directory.EnumerateFiles(dir, "*.asc"))                
{
  rasters.Add(Raster.OpenFile(file));
}
```
Than I add new Layers sequentially, with removing a previous one:
```
private MapRasterLayer last = null;
private void timer1_Tick(object sender, EventArgs e)
{
  if (i >= rasters.Count) i = 0;
  if (last != null) map.Layers.Remove(last);
  MapRasterLayer rl = new MapRasterLayer(rasters[i++]);
  map.Layers.Add(rl);
  last = rl;
}
```
It goes quite well, but crashed by starting from index 0. Probably Remove method frees some resources.

My question: is there a better way to do something like that?

**Comment by jany-tenaj** [comment]
Try to add all the layers to the map and then set the layers IsVisible properties to true or false instead of removing the layers again.

**Comment by sindizzy** [comment]
I have the same issue except with images of weather. so the recommended workflow is to load them all and then just turn on the one layer as you step through the time frame?

**Comment by jany-tenaj** [comment]
@sindizzy Based on the fact that loading to many large rasters fills up the memory I wouldn't call this recommended. But it keeps the rasters from being disposed and therefore can be used in a case like this where the rasters seem to be small enough to be loaded into memory all at once. 

If you'd want to animate large rasters you'd have to load them fresh from file and then remove them again. The problem that comes up with that is the fact that loading a raster takes some time and the animation wouldn't run fluid.

@olejniczak If your problem was solved please close the issue.
