### ISSUE TITLE
Dotspatial Form controls style

### ISSUE THREAD

**Issue by am2222** [DotSpatial/DotSpatial#1069]
Hi,
Why dotspatial forms does not follow default windows controls style?For example context menus style is in old style and also symbolizers controls such as opacity is a custom one, is it possible to make them follow the windows style?

**Comment by jany-tenaj** [comment]
Can you show images of what you expect the things to look like against what they look like?

**Comment by am2222** [comment]
<img width="922" alt="11" src="https://user-images.githubusercontent.com/4707503/31168324-d2d2d028-a901-11e7-8be9-405462a948e0.png">
<img width="547" alt="33" src="https://user-images.githubusercontent.com/4707503/31168326-d3189248-a901-11e7-937a-3e06d388e3a2.png">

@jany-tenaj  Hi,
Well I have attached two images, The first one is a context menu which appears on layers in legend control, It looks old fashion and it must look based on windows style,isn't it?
Also some controls in symbology form has also backgrounds or there is a process bar which could be replaced by windows default control

**Comment by jany-tenaj** [comment]
@am2222 Check out the changes I made in the [replaceLegendContextMenu](https://github.com/DotSpatial/DotSpatial/tree/replaceLegendContextMenu) branch.

I hope switching the context menu had the desired effect in Win 10. In Win 8 it looks just slightly different than before.

Replacing the progress bar wouldn't be a good idea because this progress bar is able to show some progress text on top of the bar. You can see the effect on pressing Apply after making a change. The default progress bar is not able to do this as far as I know.

The controls backgrounds are colored with System.Control color. I tried to switch them over to Transparent to get rid of the background but that wasn't a good idea because then they simply looked strange.
So I went the other way and made the background color of the containing tab pages System.Control colored. I'm not sure why they are colored Transparent by default but I think System.Control looks acceptable.

**Comment by am2222** [comment]
@jany-tenaj Hi,thanks very much for your reply, I'll check the new branch, It was for a while which I liked these controls to follow windows default style

**Comment by jany-tenaj** [comment]
@am2222 did you check this out?
