### ISSUE TITLE
Context Menu For Clicked Features

### ISSUE THREAD

**Issue by snahdog** [DotSpatial/DotSpatial#1072]
If there an easy way to have context menus pop up next to a feature when it is clicked on the map?

So far I have been doing it via the following:
1. Create a new MapLayer by extending existing ones.
2. Add a method that returns a context menu
3. Make my own selection function that calls the method on mouseclick and displays the context menu on the map.

It works fine, but is a bit cumbersome. Is there an easier way to do this?

**Comment by jany-tenaj** [comment]
The way you're doing it sounds correct.

You need a map function that is able to show the context menu. The functionality you descriped is not given by any current map function so writing your own is the way to go.

If you can identify your layers inside the map function you could create all context menus inside the map  function instead of creating your own MapLayers. But if not creating your own MapLayers sounds good.

**Comment by snahdog** [comment]
Thank you for your answer.
