### ISSUE TITLE
OutOfMemoryException on DotSpatial.Data.Shapefile.OpenFile

### ISSUE THREAD

**Issue by GothAr** [DotSpatial/DotSpatial#1131]
### Steps to reproduce

1. Download zip archive from [here](https://github.com/DotSpatial/DotSpatial/files/1739176/StatPlanet_Canada.zip)
2. Unzip it to some folder **DEST_FOLDER**
3. In C# project do
`using (var sf = DotSpatial.Data.Shapefile.OpenFile("DEST_FOLDER\map.shp"))
{ 
    Console.WriteLine(sf.Features.Count); 
}`

DotSpatial version: 
2.0.0-rc1 from NuGet

### Expected behaviour
Count of shapes\features is written to the output

### Actual behaviour
OutOfMemoryException is thrown on OpenFile call.

StackTrace
   at DotSpatial.Data.LineShapefile.FillLines(String fileName, IProgressHandler progressHandler, Shapefile shapefile, FeatureType featureType)
   at DotSpatial.Data.PolygonShapefile.Open(String fileName, IProgressHandler progressHandler)
   at DotSpatial.Data.Shapefile.OpenFile(String fileName, IProgressHandler progressHandler)
   at DotSpatial.Data.Shapefile.OpenFile(String fileName)
   at Read.Spatial.Program.ReadShapefile(String filePath) in ...\Read.DotSpatial\Program.cs:line 45

**Comment by VectorZita** [comment]
I downloaded the file and I can say that this problem indeed comes up. The reason is that the **map.shx** file is **wrong**, meaning that it contains the wrong point counts (i.e. byte offsets), so the **map.shp** file is not being read correctly. In specific, the **OutOfMemoryException** occurs because at some point, a value that is supposed to indicate the number of parts/points falls over a double that represents a coordinate and is bitwise-interpreted erroneously, of course, resulting in a huge number, which is, thereafter, given as a size of a requested memory chunk (impossible).

The shape-index file (shx) is corrupt, or, to put it better, not in sync. It is not corrupt because it appears to have a correct shape-index file sequence of bytes, but it does not have anything to do at all with the given map.shp file that it accompanies. I have tried to recreate the shape-index with a suitable utility and the file now loads correctly!

On a side note, it is possible to recreate the shape index file (.shx) because it merely contains such information on how to read the .shp file, that is already included within the .shp file. The provision of it simply serves to not have to read the entire shapefile to know the precise sizes of the structures that will have to be built. In specific, the shape-index file provides the capability of seeking in both directions within the shapefile. In any case, this is **not a DotSpatial bug**, it's because of an invalid shape-index file.
