### ISSUE TITLE
how identifying feature of a point shape file detail in dotspatial?

### ISSUE THREAD

**Issue by mostafahadizadeh1991** [DotSpatial/DotSpatial#1148]
I use below code to identifying the polygon shape detail and work finely. But when I use this for a point shape don't work.
anyone can help me?

```
private void mapMain_MouseDoubleClick(object sender, MouseEventArgs e)
{
      Coordinate cor =  map1.PixelToProj(e.Location);
      Extent ex = new Extent(cor.X, cor.Y, cor.X, cor.Y);
      var  mLayer = map1.Layers[0];
      IFeatureLayer il = (IFeatureLayer) mLayer;
      List<IFeature> result = il.DataSet.Select(ex);
      if (result.Count>0)  
      {
           IFeature ift = result.FirstOrDefault();
           MessageBox.Show(ift.DataRow[0].ToString()); 
       }
}
```

**Comment by jany-tenaj** [comment]
Select finds polygons with the help of a point extent because a polygon is bigger than a point and therefore Select can tell that your point extent lies within the polygon.

This doesn't work for points because Select checks whether your extent lies within the point geometry. That means your extent would have to have the same coordinate as the point you want to select.

To find a point use an extent that is bigger than a single point. To make sure your extent is big enough to find the point use the following code. This enables you to find your point at all map scales and you don't have to click on the point exactly, it gives you a little tolerance.

 ```
Coordinate c1 = e.Map.PixelToProj(new Point(e.Location.X - 4, e.Location.Y - 4));
Coordinate c2 = e.Map.PixelToProj(new Point(e.Location.X + 4, e.Location.Y + 4));
Extent ex = new Extent(c1.X, c1.Y, c2.X, c2.Y);
```
