### ISSUE TITLE
How to select the neighbors of a polygon ?

### ISSUE THREAD

**Issue by Klemet** [DotSpatial/DotSpatial#1192]
Hello ! First of all, I'd like to thank you for your work on DotSpatial. It's an amazing tool.

I apologize for my question, but I can't find a way to do what I want lately. I'm develloping a kind of cellular automata for research purposes, and **I need to find a way for the program to determine the neighbor of a cell in a grid (which will not necessarely be squared)**.

So far, using Dot Spatial, I've been able to :  

- load a shapefile that contains my grid in a "PolygonShapefile" object
- create a "Polygon Layer" object that contains the informations of the shapefile

...And now, I'm stuck. I've been trying again and again to use the "select" function of the PolygonLayer class described in the documentation to select something, anything ! But to no avail.

I've tried several things : 

- Tried to use the select function by giving it the envelopes of on cell of the grid, or the envelope of the whole grid., and asking for the "SelectionMode" to be "Touches". The resulting object (out affectedArea) is always empty, and the "selection" property of the PolygonLayer class never changes, and stays empty.

- I've tried to use the select function by giving it a feature (one of the cells of the grid). Alas, it changes nothing to me. The "selection" property is still empty, whatever selection mode I insert into the "Selection" property.

- I've tried to use the select function by giving it the index of several of the cells, with a int32; no changes, again, and "Selection" is still empty, whatever I do.

Therefore, I would be really greatfull if someone could light my lantern on the subject. I'm still a beguinner in C#, and I might be missing something really obvious; yet, thus far, my efforts to find a way to do it didn't payed. As recommanded, I downloaded the Codeplex archive to look for tutorials and exemples on the subject, but I haven't found something relevant to what I want to do.

I'll insert some exemples of my code, and will listen for any advice you'd have for me. Thank you in advance.

```
PolygonShapefile shapefile = new PolygonShapefile(filepath);
PolygonLayer shapefileLayer = new PolygonLayer(shapefile);

GeoAPI.Geometries.Envelope envelopeOfFeature = new GeoAPI.Geometries.Envelope(shapefile.Features[1].Geometry.Coordinate);
GeoAPI.Geometries.Coordinate coordExtentDuShapefile = new GeoAPI.Geometries.Coordinate(shapefile.Extent.X, shapefile.Extent.Y);
GeoAPI.Geometries.Envelope envelopeOfShapefile = new GeoAPI.Geometries.Envelope(coordExtentDuShapefile);
GeoAPI.Geometries.Envelope envelopeSelection = new GeoAPI.Geometries.Envelope();

shapefileLayer.Select(envelopeDuFeature, envelopeDuShapefile, DotSpatial.Symbology.SelectionMode.Touches, out envelopeSelection);
// Nothing changes; envelopeSelection is empty, and shapefileLayer.Selection is too.

shapefileLayer.Selection.SelectionMode = DotSpatial.Symbology.SelectionMode.Touches;
shapefileLayer.Select(5);
// Same thing

shapefileLayer.Select(shapefile.Features[1]);
// Same thing
```

**Comment by VectorZita** [comment]
This may be a little late, but it would really help if you would explain a bit, what it is that you want to achieve in specific. The code you pasted is a bit weird and it appears that it cannot perform any reasonable kind of selection, indeed. But it is also difficult to understand what you want to do from what you are saying. For example, what do you expect from the selection? To see it highlighted on the map?

If you can give a good example of what you want to do, an answer may be within reach!

**Comment by Klemet** [comment]
Hello VectorZita, and thanks for the answer : ).

I did move on to the GDAL/OGR assembly in C# to do what I wanted to do; but as many of the functions of GDAL/OGR have been lost in translation in C#, I can always do with a alternative : ).

I was creating a cellular automata imitating forest fires. Therefore, I needed to be able to select the neighboring cells/polygon of a given cell/polygon (the ones that touches it) in order to then calculate a probability of the fire diffusing to them, based on the value they contain (age of the fire).

That is why I was looking for a function that would allow me to select the neighbors of a cells, and to be able to get their ID, for exemple.

**Comment by VectorZita** [comment]
I see. So what you want is a geometric relation (neighboring contact, in specific). To support your automaton, you probably have to create in advance all the cells as geometric shapes. Furthermore, I don't think the DotSpatial geometry engine (GeoAPI and NTS) would be able to help you a lot with your approach, in the sense that there are far better methods. If I understand correctly, you want to find which cells touch each cell by using a geometric method, which is not the most lightweight geometric relation task overall.

What you need is a group of cells, **plus** a relational structure which can immediately give you the neighbors of each cell. In order to achieve such a thing, it would more sense to create that structure along with the creation of the polygon cells in the beginning, rather than creating the cell geometries ad hoc and trying to find the neighbors thereafter. That is, create a polygon, then create its direct neighbors and store them in the polygon (or a structure that associates polygons to neighbors).

However, I don't know if you are given the geometries in advance, so maybe you cannot do that. In that case, what you would be trying to achieve relies heavily on **good geometry**. That is to say that I don't know the thresholds of the geometry algorithms of the NetTopologySuite implementations (which are technically the Feature.Geometry objects).

So, if I understand correctly, you want to choose a polygon, and find and select all the neighboring polygons. Unfortunately, DotSpatial does not do this thing "out-of-the-box" and spatial relation analysis is not DotSpatial's primary concern. However, the NTS geometries as an implementation of the GeoAPI are quite strong in spatial 2D relations, so there might be a way. From what I can see at the moment, first of all I have to tell you why what you attempted to do does not work.

In your first call, **Select**, where you passed in an envelope that consists of only a single point, tries to find all features that intersect with this point. This is, of course only the feature you have in mind (your polygon) because the point you passed in the envelope was a point of that feature (unless other features overlap).

In your second call, **Select** was passed in the argument **5**, which means select the 5th feature. This, once again, does not do what you want.

What you want can only be done by somewhat of a "hack" at that point. First of all, you have to get the feature you are interested in, say **polygon1**. Then you have to take its envelope by: 

**Envelope featureEnv = polygon1.Geometry.EnvelopeInternal;**

and this is the envelope of the geometry of this feature. Then you have to expand this envelope by a small distance as in:

**featureEnv.ExpandBy(10);**

for example. Keep in mind, this value (10 here) reflects true metric units in the coordinates you are using. So if you are working with latitudes and longitudes, 10 is not what you want. If you are working with X and Y, it's more like 10 meters or so (if your X and Y are not in km of course!!).

Afterwards, you can call the **select** method of the **FeatureLayer**, and supply this **featureEnv** along with the selection method being "Intersects", so that whatever intersects this expanded region will be selected! This will select everything your polygon overlaps when expanded slightly (that is, **all the neighbors that touch the polygon**, given that the polygons are correctly located in the **FeatureSet** and their geometries "gracefully" touch each other). You can then get whatever is selected by the Selection object in your FeatureLayer.

The bad thing is that your feature also gets selected because it is very much contained within its expanded envelope(!) But you already know which feature it is (polygon1) so you can check and omit it when doing whatever else you wish with your selected polygon features thereafter.

I hope this gives you some insight into the problem. If you have any further questions, let us know!

Also, if some other contributor may care to correct me or add to the idea, feel free to, as I am not totally sure if there is some other way/plugin for this type of functionality, that I have potentially missed!

**Comment by Klemet** [comment]
Thanks a bunch for the detailed answer : ) ! It really lights my lantern on that case !

Indeed, I thought in retrospective that DotSpatial might not have been created with this kind of operations in mind; that is why I finally turned to GDAL/GEOS, which are the reference in other languages such as R for spatial analysis operations like this one.

I did thought of the hack your were proposing, but I also thought that it would take to much time and could lead to errors. I could have found a way to increase the envelope based on the cell area so as to automatically scale the expansion, but I would quickly reach a problem of optimization, I believe :s.

To give a bit more details on the practical aspects of what I was attempting to do, it was going on like this :

- I used R to create the cells (polygon), and to save them in shapefile.
- I then wanted to use DotSpatial to read the informations of the geometries in the shapefile
- Afterward, for each cell, I would have created a list of neighbors (a list of **Int** where each **Int** is a cell ID) by using a neighbor selection.
- The list of neighbors of a cell would then go into a list of lists of **Int**s, therefore allowing me to have all of the spatial relations of the grid contained in the list of lists before the simulation starts, and greatly facilitating everything afterward. The program would just have to read the list at a particular index to know which cell have which neighbor, and no spatial operations would have to take place.

Thanks to your detailed commentary, I believe that I can keep going with GDAL in peace : ). I might use DotSpatial for other things afterward, but for now, I'll concluded that GDAL might be more compatible with what I attempt to do.

**For further readers interested in the issue, I'll quickly detail here what can be used with the GDAL/OGR assembly in C# to do the trick** : 

- Load your shapefile into a **OSGeo.OGR.DataSource** object using the **Ogr.Open** function.
- Transform the **DataSource** object into a **OSGeo.OGR.Layer** object using **.GetLayerByIndex(0)** on the **DataSource** object.
- The **Layer** object contains **Features** that contains **geometries**. **Layer.GetFeature(Int)** gives you the feature with the given ID as an **Int**, and **Layer.GetFeature(Int).GetGeometryRef()** gives you all of the geometries contained in the feature (but you can select a particular geometry if the features contains multiples ones. In my case, each of my features was a single cell = single polygon, so I didn't had this issue).
- The geometry object in GDAL contains methods like "**Within**" or "**Touches**" which give a **boolean** object telling you if the condition is true. To use the method, you only have to input another geometry. Everything can be done from there with loops.
- Example : 

`Layer.GetFeature(IDOfCell1).GetGeometryRef().Touches(Layer.GetFeature(IDOfCell2).GetGeometryRef())`

If true, add to neighbor list. If not, don't add to neighbor list.

- Optimization can be done by doing those operations in parallel; but be carefull, because 1) the Layer object isn't thread-compatible, meaning you should transform it into a list of geometries if possible and use it instead, and 2) instead of looking at all the cells of the grid to check if they touch a given cell (which takes a lot of time for big grids with millions of cells), one can create an algorithm using sub-zones of the grid to greatly reduce the number of operations to be done.

Thanks again for everything, VectorZita, I hope I did not waste your time ! Have a great day !
