### ISSUE TITLE
PreventCollisions for Symbology

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1214]
DotSpatial version: 2.0

I see that labels have the PreventCollisions property. is there such a thing for Symbology? Was comparing my DotSpatial output to MapWindow and noticed that in MW when there are too many point symbols it seems to implement a collision algorithm so as not to clutter the map. Does DS have something similar?

**Comment by VectorZita** [comment]
Unfortunately, I have not found out something thus far, but maybe I have not looked that deep. The only loosely relevant thing I have found is the **DuplicationPreventer** class which removes unnecessary points from lines and polygons prior to drawing.

However, the Map control has a property called **CollisionDetection**, which I couldn't find being used anywhere in the source code. Maybe it was a desired feature and it never saw the light (yet). In any case, this is not very hard to implement and it **definitely** is worth doing! I might take a look into it soon.

The property description for **CollisionDetection** states:
> Gets or sets a value indicating whether the point layers in the map will only draw points that are more than 50% revealed. This should increase drawing speed for layers that have a large number of points.

In any case, I believe the Map is not the place for this type of functionality, I guess it would serve better if it were defined in the point symbolizer directly, so that different layers can have different settings (let alone the actual drawing takes place within the layers).

**Comment by sindizzy** [comment]
Cool thanks for the info.

**Comment by VectorZita** [comment]
As you probably already know, preventing collisions is not only important to avoid cluttering, it is of **utmost** importance because, otherwise, the map begins to lag slightly for large point datasets when panning/zooming around. By "large", I mean anything over  ~10000-20000 point features with any symbolizer (on a relatively fast computer, no less). Although these numbers appear to be rather large, as you probably know very well, such dataset sizes are easily the **baseline** (or even below that) in a production environment. So this matter is of utmost importance to ensure a _tolerable_ fps measure for casual use.

**Comment by sindizzy** [comment]
I totally agree. I have a shoreline polygon feature class that easily has 200K vertices. At a global level the user cant discern between the 50 vertices next to each other. It would speed up rendering if not all vertices are required to be displayed and would not make a difference to the user anyway.

**Comment by jany-tenaj** [comment]
I think this was fixed by #1461
