### ISSUE TITLE
Determine if ProjectionInfo is projected or geographic

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1217]
If you have a spatial reference that is defined as 
`pi As ProjectionInfo`

Is there a suggested way to  determine if it that SR is projected or geographic?

**Comment by VectorZita** [comment]
As I recall from some playing around with the map functions, a rather long time ago, I had seen in the MapFunctionMeasure.cs file (for the measure extension) the use of **IsLatLon** property. To the best of my knowledge thus far, this is the only thing I have seen that appears to discriminate between geographic and projected coordinate systems. Take this with a grain of salt as I have not searched high and low, but if you check the **GetDist** function in **MapFunctionMeasure.cs**, this is what is used and, since this function is definitely one that has to be based on whether a current projection is geographic or projected, **IsLatLon** appears to do the trick.

If there is something else that was meant to provide this discrimination between projected and geographic systems, I would also like to know.

**Comment by sindizzy** [comment]
I tried IsLatLon and found a couple of cases where it didn't work. Cant remember the exact cases though. I am using this:

`If fs.Projection.Unit.Meters <> 1 Then Throw New Exception("Featureset projection is not geographic.")
`

I can't remember where I got this or who recommended it.

**Comment by VectorZita** [comment]
After taking a deeper look into the **Reproject** class (it's static), I think it's fair to assume that such a thing can be deduced from looking into the original source code of the **ReprojectPoints()** method. If you check it out (file Reproject.cs), you can see that it calls **ConvertToLatLon()** at some point. This is the defining call, which converts to latitude/longitude when your coordinates are projected. Inside that function, apart from some adjustments (such as de-scaling and de-offsetting), the "heart" of the method lies in the call to **source.Transform.Inverse()**.

I guess it is fair to assume that this will only execute if there actually **is** a transform defined for that **ProjectionInfo**. Seeing that the original development was based on checking whether **source.Transform** is not null, I guess you can bet on that. If there is a Transform object defined, it probably generally means that this is a projected system, if it is null, it is a geographic spatial reference.

I have also checked all available **ITransform** implementations and I saw there is a **LongLat** one, so I think you should check that as well. So, to wrap up, the next thing you can test is whether the Transform property of your **ProjectionInfo** object is null. If it is null, this is a Geographic Spatial Reference object. Also, if it is not null, check if the Transform property is a LongLat object, in which case it probably still is a Geographic Spatial Reference.

If this doesn't do the trick, I don't know if anything else should, because all this is based on checking what the actual code does, so, unless I have missed something (take a look at the original source code too, just to be sure), there doesn't appear to be any provision for such a check.

Check it out and let me know if you were successful!

**Comment by sindizzy** [comment]
I'm not as up to speed on the reprojection maths so Ill take your word for it. I will add the logic to my project and then run some tests,
