### ISSUE TITLE
Map Frame Graphic Drawing

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1224]
Hello
I was draw UTM Grid on map class inside the Onpaint Method , but i see every change on map cause grid line refresh so i deiced to check and find solution , maybe MapFrame class is better place for drawing but i get error !
may you help me ? Grid line just redraw when extend view change.
this is my code

```
private void DrawHorizentalLine(double step)
{
   for (double i = -90.0; i <= 90.0; i += step)
   {
       this._pt1 = this.ProjToPixel(new Coordinate(this._startPoint.X, i));
       this._pt2 = this.ProjToPixel(new Coordinate(this._endPoint.X, i));
       this._mapGridLineDrawer.DrawLine(this._pen, this._pt1, this._pt2);
       this._mapGridLineDrawer.DrawString(i.Equals((double) 0.0) ? "0" : ((i < 0.0) ? (Math.Abs(i) + " N") : (i + " S")), this.Font, this._brush, (PointF) this._pt1);
   }
}
```

```
private void DrawVerticalLine(double step)
{
   for (double i = -180.0; i <= 180.0; i += step)
   {
       this._pt1 = this.ProjToPixel(new Coordinate(i, this._startPoint.Y));
       this._pt2 = this.ProjToPixel(new Coordinate(i, this._endPoint.Y));
       this._mapGridLineDrawer.DrawLine(this._pen, this._pt1, this._pt2);
       this._mapGridLineDrawer.DrawString(i.Equals((double) 0.0) ? "0" : ((i < 0.0) ? (Math.Abs(i) + " W") : (i + " E")), this.Font, this._brush, (PointF) this._pt1);
   }
}
```

Map Class :

```
protected override void OnPaint(PaintEventArgs e)
{
   if (!this._geoMapFrame.IsPanning)
   {
       Rectangle clipRectangle = e.ClipRectangle;
       if (clipRectangle.IsEmpty)
       {
           clipRectangle = base.ClientRectangle;
       }
       if ((clipRectangle.Width >= 1) && (clipRectangle.Height >= 1))
       {
           using (Bitmap bitmap = new Bitmap(clipRectangle.Width, clipRectangle.Height, PixelFormat.Format32bppArgb))
           {
               using (Graphics graphics = Graphics.FromImage(bitmap))
               {
                   using (SolidBrush brush = new SolidBrush(this.BackColor))
                   {
                       graphics.FillRectangle(brush, new Rectangle(0, 0, bitmap.Width, bitmap.Height));
                   }
                   using (Matrix matrix = new Matrix())
                   {
                       matrix.Translate((float) -clipRectangle.X, (float) -clipRectangle.Y);
                       graphics.Transform = matrix;
                       this.Draw(graphics, e);
                       MapDrawArgs args = new MapDrawArgs(graphics, clipRectangle, this._geoMapFrame);
                       foreach (IMapFunction function in from _ in this.MapFunctions
                           where _.Enabled
                           select _)
                       {
                           function.Draw(args);
                       }
                       PaintEventArgs args2 = new PaintEventArgs(graphics, e.ClipRectangle);
                       base.OnPaint(args2);
                   }
                   e.Graphics.DrawImageUnscaled(bitmap, clipRectangle.X, clipRectangle.Y);
                   if (this.MapFrame.LayersVisible)
                   {
                       try
                       {
                           this._mapGridLineDrawer = base.CreateGraphics();
                           Pen pen = new Pen(this._colorPen.IsEmpty ? Color.Blue : this._colorPen) {
                               DashPattern = this._dashValues
                           };
                           this._pen = pen;
                           this._brush = new SolidBrush(this._colorBrush.IsEmpty ? Color.Blue : this._colorBrush);
                           this._startPoint = this.PixelToProj(new Point(0, 0));
                           this._endPoint = this.PixelToProj(new Point(base.Width, base.Height));
                           double num = this._endPoint.X - this._startPoint.X;
                           if (num >= 180.0)
                           {
                               this.DrawVerticalLine(0x2d);
                               this.DrawHorizentalLine(0x2d);
                           }
                           if ((num < 180.0) && (num >= 90.0))
                           {
                               this.DrawVerticalLine(10.0);
                               this.DrawHorizentalLine(10.0);
                           }
                           if ((num < 90.0) && (num >= 20.0))
                           {
                               this.DrawVerticalLine(5.0);
                               this.DrawHorizentalLine(5.0);
                           }
                           if ((num < 20.0) && (num >= 15.0))
                           {
                               this.DrawVerticalLine(1.0);
                               this.DrawHorizentalLine(1.0);
                           }
                           if ((num < 15.0) && (num >= 5.0))
                           {
                               this.DrawVerticalLine(0.5);
                               this.DrawHorizentalLine(0.5);
                           }
                           if ((num < 5.0) && (num >= 0.25))
                           {
                               this.DrawVerticalLine(0.25);
                               this.DrawHorizentalLine(0.25);
                           }
                           this._pen.Dispose();
                           this._brush.Dispose();
                       }
                       catch (Exception)
                       {
                           MessageBox.Show("No more Zoom...Contant Us");
                       }
                       this._mapGridLineDrawer.Dispose();
                   }
               }
           }
       }
   }
}
```

**Comment by DavisMillier** [comment]
Hello @sindizzy 
when i use my code in Map.cs and Onpaint method i use base.create graphic but when i use it another class _mapGridLineDrawer thrown error cause it is null, i should to have UTM grid line with out refresh when map.refresh or invalidate call , In fact, it needs to be Redraw grid when it's zoomed in/out or moved (Pan).

**Comment by sindizzy** [comment]
You have to have an object against where you can create graphics. Have you tried e.Graphics?

**Comment by VectorZita** [comment]
@DavisMillier, I would suggest not tampering with the code base at such a low level to alter a behavioral aspect of the Map control, especially when this behavioral aspect is the precise one that the entire codebase was created to facilitate...i.e. **drawing**.

Why get down to GDI+ when the Map itself offers you the way to do whatever you want with layers.

My suggestion is to create a **MapLineLayer** (say we call it **gridLayer**) and keep a reference to it inside your program. Add this to the **DrawingLayers** of the **Map** you are using (so that it won't appear in the legend, and it won't have labels, i.e. it will be hidden). The Map control offers an event called **ViewExtentsChanged**, sounds to me like that's exactly what you want. You can hook a handler to that event, which will clear the **gridLayer** and recreate it as needed based on the new extents. You know what I mean "recreate" of course. You can add the lines you want as **Features** with a **LineString** geometry, just as you would create new features. This way you exploit the already well-tested available functionality without wandering into "uncharted" GDI+ territory using error-prone code. Guess what else you gain by doing this... you can use a specific symbolizer for your grid, such as dotted lines, colors, everything, whereas using GDI+ you'd have to manage these things by yourself (I know it's not too much hassle with GDI+ either, but "hacks" like that should really be the last resort in a large library when one wishes a long not-too-cumbersome lifetime of whatever application they are basing on top that library, especially when it is rather robust, as is DotSpatial).

If you wish to try the above methodology, you will soon discover this works as an **overlay,** rather an "_underlay_", that is, it is drawn on **top** of everything else, not the other way around. This is easily fixable, but **then** you will need to tamper with the **MapFrame.cs** code, and this will be only to make your layer draw itself before every other layer in the corresponding **Initialize** function. We'll see to it when you get there, so don't worry about that for the moment.

In any case, overriding **OnPaint** is only meant when you know precisely what you are doing, and it also means you expect your drawing logic to occur **quite often** (as in, "all the time", or round the message-loop, for some...). So, give all of this some thought, and let us know.
