### ISSUE TITLE
How to buffer the line elements  with dotspatail 2.0

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1229]
How do dotspatail 2.0 project line elements? I need to do buffering. At present, I take every point out of the line, do projection on points and then combine them into lines. This is much less efficient. What's a good way? I haven't found a projection method for Geometry and line elements.

**Comment by VectorZita** [comment]
The **Geometry** property of every **IFeature** instance also contains a method called **Buffer**(...). This method creates a new Geometry that represents the buffered geometry. You can create a new Feature based on this Geometry! If your original feature had a **LineString** geometry, then the created feature geometry will correspond to what you are trying to achieve. Check out the **IFeature.Geometry.Buffer**(…) method.

**Comment by BeinerChes** [comment]
Where can I find  dotspatail 2.0 source code?

**Comment by VectorZita** [comment]
Right in this repository, you can browse and see the source code of the entire project. If you want to download it, in the main page (e.g. https://github.com/DotSpatial/DotSpatial), you can click Clone or Download (green button towards the top-right of the page), and you will receive a large file that you can unzip and open in Visual Studio.

If, however, you need the source code of the buffer method, it is a little bit more complicated, but you can look for it in the NetTopologySuite library (https://github.com/NetTopologySuite/NetTopologySuite). There, you can do the exact same things to browse the source code.

Apart from that, you don't need any of this to achieve what you specifically asked for. The functionality is already built-in and in place and you can use it through the **Buffer** method of the Geometry of any Feature.

**Comment by xc398013967** [comment]
@VectorZita   thank you very much
 I have a NetTopologySuite library,but I can not download the source code, Always hints at download failure，So I can't find the Line Feature projection method ,Only Reproject.ReprojectPoints() methord can be found,Now I have to buffer the line elements, so I need to transform the geographical elements of the line elements into projection coordinates.

**Comment by VectorZita** [comment]
I understand you are confusing the two things together, and a third thing that you are not even considering. Maybe you could share some source code as a small example of what you are trying to achieve, this would be very helpful, so that we can point you to the right direction.

That said, do not mistake **Reproject** with the **projection** you mean. When you say "project", you probably mean "take a point and find its perpendicular projection onto a line". **Reprojection** is a very different animal, in a sense, having little to do with the classic vector projection you are referring to. It means "take a set of coordinates from some _mapping_ and transform them to a different set of coordinates in some other _mapping_" (well, there's much more to it, but that should suffice as you are not asking about this in specific).

I don't know why you cannot get the buffer of the line features. Like I said, if you can share some source code, we can take it from there. As for NetTopologySuite, you can browse the code online too, but I doubt this would be of substantial help. It is a very well-written and quite optimized library, you will have to dig deep to find the exact source-code excerpts that perform what you are looking for. The simple question is, are you interested in _how the source code does it_ (the buffering), or are you just interested in _achieving it in your own application_?

**Comment by xc398013967** [comment]
@VectorZita   thank you very much 
Because my map  is geographical coordinates system ,I need to buffer the line element，so I think I need to buffer the line into a projection coordinate system, so the buffer radius is handled and accurate.

 private void BufferSegment(Feature feature, double distance)
        {
            Feature pFeature = (Feature)feature.Buffer(distance, EndCapStyle.Square);//buffer  
            featureSet.Features.Add(pFea);
        }

The above code here is the feature that needs to be buffered. At present, this feature is geographic coordinates. I need to switch to projection coordinates separately to specify the radius distance of the buffer.

**Comment by VectorZita** [comment]
I understand... so you want **this** animal after all. I can suggest two ways to deal with this:

**1)** _Back-and-forth_
You can reproject the coordinates to any projection that is **fairly conformal**, such as some UTM zone or any TM set up around the meridian crossing, say, the midpoint of your line feature. Then, through these coordinates, you can get the buffered feature (this would have a polygon geometry), and reproject this feature back to geographic coordinates. I am assuming you are also visualizing in geographical coordinates, so what you are viewing at the map is, in reality, an equirectangular projection (plate carrée) of your area.

**2)** _Straightforward_
Starting from the premise that the overall dimensions of your geometry (line feature, in this case) are not absurdely large (I would go with "less than a few tens of km/miles"), you could also "misuse" the **Buffer(…)** method of the **IGeometry**. The straightforward problem, here, is how you define _distance_ from geographic (geodetic, actually, if we are talking about WGS84, _you know that there is a difference between geographic and geodetic_) coordinates. Therefore, around your location, you have to provide a _distance_ value that corresponds to decimal degrees. This is **of course** suboptimal, but it can help you if you are drafting or don't care about tremendous accuracy. You can go about this as follows:

Using a linear approximation on the earth ellipsoid, you can [convert your line-midpoint to the corresponding length of 1 degree](https://en.wikipedia.org/wiki/Geographic_coordinate_system#Expressing_latitude_and_longitude_as_linear_units). This will give you, say, **L** meters. But you already know how much you want to buffer, it's your **distance** parameter, at the units that you already know (I will assume meters here for the sake of ease, because the formula in the link also provides meters). You can calculate the corresponding "distance" **in degrees**, from this **distance** in meters, because you know that 1 degree corresponds to **L** meters around your area. So:

`distance_in_degrees = distance / L` (you divide your desired distance with the 1 degree-length you calculated, after potentially accounting for units, of course)

This is the value that you want to "feed" to the **Buffer**(…) method of the **Feature** and it will create a buffer that will approximate (quite adequately, I would say) your desired buffer zone. Because the coordinates themselves are in decimal degrees, the distance will also be in degrees and things will, at least, work out.

Of course, both are approximations. The most optimal way is to offset the start and end point in the perpendicular direction using ellipsoid geometry and connecting the points (for example, clockwise), however, one of the two ways above should suffice, at least if you are not "pricing" your area units ;)
