### ISSUE TITLE
Question: Can someone show me how to add the ShapeEditor buttons?

### ISSUE THREAD

**Issue by Ryan-Leroux** [DotSpatial/DotSpatial#1338]
I'm new to the DotSpatial library and I'm having issues adding the ShapeEditor buttons/functions to the spatialToolStrip.

Can someone point me in the right direction? I wasn't able to find many good "tutorials".

Thanks!!

**Comment by jany-tenaj** [comment]
Add the shape editor plugin as shown on the following [wiki page](https://github.com/DotSpatial/DotSpatial/wiki/Plugins).

**Comment by Ryan-Leroux** [comment]
I'm unable to get this to work - the instructions aren't the greatest.

Are there any available tutorials that show more specific details?

Thanks.

**Comment by jany-tenaj** [comment]
Ok if this isn't enough then check out [the getting started guide](https://github.com/DotSpatial/DotSpatial/wiki/Getting-started). If you have your program build like this, copying over the files into the correct folder should make sense enough, because afterwards the plugins get loaded automatically.
