### ISSUE TITLE
The problem of topology precision is compared with ArcGIS

### ISSUE THREAD

**Issue by damonsmart** [DotSpatial/DotSpatial#1378]
Dotspatial has been in use for some time
I found some differences between the topological methods in GeoAPI and ArcGIS
For example,
In the same shape file, I want to use the OVERLAPS method to test surface overlaps
An error was found in ArcGIS
However, four errors were found in dotSpatial
I want to find some methods about precision modification, because it can be configured in ArcGIS
But I did not find it in dotspatial
I hope you can help me answer my doubts

**Comment by MatthiasSchilder** [comment]
As far as I can tell, GeoAPI merely contains interfaces, the implementation comes from NetTopologySuite (NTS). DotSpatial had forked NTS at version 1.14.4, and not updated since. The original project has moved on to version 2.something, so maybe the odd behaviour was adressed in the meantime.

I suggest you file an issue at https://github.com/NetTopologySuite/NetTopologySuite with a code sample. If it turns out your issue was actually adressed, maybe the DotSpatial team could think about syncing its fork with upstream and updating the packages in DotSpatial then.

**Comment by jany-tenaj** [comment]
This is a nts issue.
