### ISSUE TITLE
DotSpatial.Controls.dll targets a platform whose toolbox items cannot be enumerated dynamically

### ISSUE THREAD

**Issue by gabrielgcma** [DotSpatial/DotSpatial#1476]
### Steps to reproduce

1. Follow the [getting started](https://github.com/DotSpatial/DotSpatial/wiki/Getting-started) instructions up until you need to add the DsControls toolbox.
2. Select "Choose Items".
3. Search for "DotSpatial.Controls.dll" and select it.

DotSpatial version: V4.0.656 (latest)
Project .NET version: .NET 6.0
Visual Studio version: 17.4.2

### Expected behaviour

DotSpatial controls should be added to the VS toolbox.

### Actual behaviour

![image](https://user-images.githubusercontent.com/93090939/205317437-81fbd347-58bd-42c5-a589-7dbc2697c503.png)

**Comment by gabrielgcma** [comment]
Workaround: it seems that installing DotSpatial.Controls directly from NuGet packages fixes the problem (because it automatically inserts the controls to the toolbox).

**Comment by jany-tenaj** [comment]
This seems to be a [Visual Studio issue](https://developercommunity.visualstudio.com/t/still-cannot-add-a-winforms-control-to-the-vs-tool/1626082). 
I'm going to change the getting started guide so it will work without referencing nuget and without adding things to the toolbox. If you mix the dlls from the zip file to get the plugins with the files from the nuget file you get an error because they aren't compatible.
