### ISSUE TITLE
ExtendBuffer is not working in DS 1.6 ?

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#661]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25372)**

**[VladimirArias](http://www.codeplex.com/site/users/view/VladimirArias)** wrote 2014-04-08 at 20:55
I'm trying to develop an navigation software using DotSpatial, I need to rotate the map to follow a route.

When ExtendBuffer is True it works bad.

Thanks and best regard.

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-04-08 at 21:36
I believe you are a not first who noticed this :) 

<a href="https://dotspatial.codeplex.com/discussions/538511 rel="nofollow">https://dotspatial.codeplex.com/discussions/538511</a>

[https://dotspatial.codeplex.com/discussions/435904](https://dotspatial.codeplex.com/discussions/435904)

**Comment by ldrvl31** [comment]
Hello,

I have been struggling to make Dotspatial with ExtendBuffer work better, as I also need it for map rotation, and I thought that sharing the little I have achieved so far might be helpful for people who, like I do, would like to see a full implementation of this feature.
The results are promising : panning is working correctly, the geographic coordinates are correct, but there is certainly a lot more to be done.

Firstly, to correct the conversion between a single point location and its equivalent geographic coordinate, I assumed that the geographic extents would be 3 times larger than the image rectangle, and changed the following for the PixelToProj and ProjToPixel methods in ProjExt.cs.


	public static Coordinate PixelToProj(this IProj self, Point position)
	{
		double x = Convert.ToDouble(position.X);
		double y = Convert.ToDouble(position.Y);
		if (self != null && self.GeographicExtents != null)
		{
			if (_extendBuffer)
			{
				PointF point = new PointF(position.X, position.Y);

				x = point.X * (self.GeographicExtents.Width / 3) / self.ImageRectangle.Width + self.GeographicExtents.MinX + self.GeographicExtents.Width / 3;
				y = self.GeographicExtents.MaxY - self.GeographicExtents.Height / 3 - point.Y * (self.GeographicExtents.Height / 3) / self.ImageRectangle.Height;
			}
			else
			{
				x = x * self.GeographicExtents.Width / self.ImageRectangle.Width + self.GeographicExtents.MinX;
				y = self.GeographicExtents.MaxY - y * self.GeographicExtents.Height / self.ImageRectangle.Height;
			}

		}
		return new Coordinate(x, y, 0.0);
	}


	public static Point ProjToPixel(this IProj self, Coordinate location)
	{
		if (self.GeographicExtents.Width == 0 || self.GeographicExtents.Height == 0) return Point.Empty;
		if (location == null) return Point.Empty;
		try
		{
			int x;
			int y;

			if (_extendBuffer)
			{
				float xF = Convert.ToSingle((location.X - self.GeographicExtents.MinX - self.GeographicExtents.Width / 3) *
										3 * (self.ImageRectangle.Width / self.GeographicExtents.Width));
				float yF = Convert.ToSingle((self.GeographicExtents.MaxY - self.GeographicExtents.Height / 3 - location.Y) *
										3 * (self.ImageRectangle.Height / self.GeographicExtents.Height));
				
				PointF point = new PointF(xF, yF);

				x = Convert.ToInt32(point.X);
				y = Convert.ToInt32(point.Y);
			}
			else
			{
				x = Convert.ToInt32((location.X - self.GeographicExtents.MinX) *
									(self.ImageRectangle.Width / self.GeographicExtents.Width));
				y = Convert.ToInt32((self.GeographicExtents.MaxY - location.Y) *
										(self.ImageRectangle.Height / self.GeographicExtents.Height)); 
			}
			return new Point(x, y);
		}
		catch (System.OverflowException)
		{
			return Point.Empty;
		}
	}

The _extendbuffer boolean is just a replicate of the Extendbuffer property retrieved from MapFrame.cs :

in ProjExt.cs :


	public static bool ExtendBuffer
	{
		get { return _extendBuffer; }
		set { _extendBuffer = value; }
	}

in MapFrame.cs :

	[Serialize("ExtendBuffer")]
	public bool ExtendBuffer
	{
		get { return _extendBuffer; }
		set { 
			_extendBuffer = value;
			ProjExt.ExtendBuffer = value;
			}
	}

The issue with the changes made for these two methods for ExtendBuffer is that they can be called from MapFrame or MapArgs objects (which both implement IProj) and for MapArgs, the geographic extents are NOT 3 times larger than the image rectangle.
One example for ProjToPixel is the Initialize method which instructs the map frame to draw content from the specified regions to the buffer. 


	MapArgs args = new MapArgs(ClientRectangle, ViewExtents, bufferDevice);
	GraphicsPath gp = new GraphicsPath();
	foreach (Extent region in regions)
	{
		if (region == null) continue;
		Rectangle rect = args.ProjToPixel(region);
		gp.StartFigure();
		gp.AddRectangle(rect);
	}


The self.ImageRectangle is the ClientRectangle here, which is not the same size as the MapFrame.ImageRectangle when ExtendBuffer is true, as you can see below :


	public Rectangle ClientRectangle
	{
		get { return new Rectangle(0, 0, _width, _height); }
	}

	public Rectangle ImageRectangle
	{
		get
		{
			if (_extendBuffer) return new Rectangle(_width / 3, _height / 3, _width / 3, _height / 3);
			return new Rectangle(0, 0, _width, _height);
		}
	}

I could not find an easy solution to this problem, however the content is correctly drawn to the buffer, as I understand it the pixel region is too large but contains the needed region.

Secondly, I fixed the pan functionality which was bugged (after mouse up the extent was moving).
To do this, I removed the expand for the BufferExtents in MapFrame.cs, since as I understood it ViewExtents is already extended.

	public Extent BufferExtents
	{
		get
		{
			if (_extendBuffer)
			{
				Extent ext = ViewExtents.Copy();
				//ext.ExpandBy(ext.Width, ext.Height);
				return ext;
			}
			return ViewExtents;
		}
	}

I also modified the BufferToProj(Rectangle rect) method used for setting the extent after panning, by correcting the rectangle used to fit the view.


	public Extent BufferToProj(Rectangle rect)
	{
		Point tl;
		Point br;

		if (ExtendBuffer)
		{
			Rectangle bufferRectangle = new Rectangle(rect.X - _width / 3, rect.Y - _height / 3, _width, _height);

			tl = new Point(bufferRectangle.X, bufferRectangle.Y);
			br = new Point(bufferRectangle.Right, bufferRectangle.Bottom);
		}
		else
		{
			tl = new Point(rect.X, rect.Y);
			br = new Point(rect.Right, rect.Bottom);
		}

		Coordinate topLeft = BufferToProj(tl);
		Coordinate bottomRight = BufferToProj(br);
		return new Extent(topLeft.X, bottomRight.Y, bottomRight.X, topLeft.Y);
	}


These changes allowed me to make Dotspatial work better with ExtendBuffer, however there are still some bugs, for example displaying a raster image on the map doesn't work properly.
This is apparently due to other pixel/proj conversions used that have to be modified for ExtendBuffer.
I would very much like to see this feature fully implemented.
Is anyone is working on this or is willing to help ? Please let me know.

Thanks and best regards :)

**Comment by mogikanin** [comment]
Hi @ldrvl31 , thanks for posting this. Would you like to provide your changes as pull request to be merged into repo? One remark - do you understand why used this magic number 3? If so, can you add an explanation somewhere in code? And also, we need to use constant field from one place for it. e.g. it might be
```
interface IMapFrame
{
......
int ExtendBufferCoefficient {get;}
}


class MapFrame : IMapFrame
{
int ExtendBufferCoefficient {get; {return 3;}}
}
```

**Comment by ldrvl31** [comment]
Hi @mogikanin , thank you for your answer, I am currently working on it (I simplified by changing the ImageRectangle used in PixelToProj and ProjToPixel when applied to a MapFrame instead of changing the calculation as I did previously) and I am testing it, I will provide the changes after that by making a pull request as you suggested (I'm not yet familiar with the process for committing changes).

About the magic number 3, it is explained a bit in the ExtendBuffer property , but I can add comments to clarify.

        /// <summary>
        /// Gets or sets whether this map frame should define its buffer
        /// region to be the same size as the client, or three times larger.
        /// </summary>
        [Serialize("ExtendBuffer")]
        public bool ExtendBuffer
        {
            get { return _extendBuffer; }
            set { 
                _extendBuffer = value;
				//CGX
                ProjExt.ExtendBuffer = value;
				//End CGX
                }
        }

The number 3 is already used several times directly in the code, for example in CreateBuffer()

        private Bitmap CreateBuffer()
        {
            if (_parent != null)
            {
                _width = _parent.ClientSize.Width;
                _height = _parent.ClientSize.Height;
            }
            else
            {
                _width = 1000;
                _height = 800;
            }
            if (_height < 5) _height = 5;
            if (_width < 5) _width = 5;

            _backView = new Rectangle(0, 0, _width, _height);
            if (_extendBuffer)
            {
                _backView.X = _width;
                _backView.Y = _height;
                _width = _width * 3;
                _height = _height * 3;
            }

            return new Bitmap(_width, _height);
        }

It is a good idea to use a constant field, I will see what I can do.

**Comment by mogikanin** [comment]
Yes, I saw xml comment for `ExtendBuffer`, but don't know why used 3 :) Why not 4 or 5?

**Comment by ldrvl31** [comment]
I think that ExtendBuffer was created so that you can pan the map all the way in every direction and the hidden area will appear, so three times the  is the size of the client is the minimum size you need just to do that ! I need the ExtendBuffer for rotating the map so the value I need is different but three works ok most of the time.

**Comment by ldrvl31** [comment]
Hi @mogikanin , I finally took time to provide my changes as pull request to be merged into repo.
However the pull request failed.. 
To do the pull request, I created a fork from the dotspatial:master, commited changes to the master brank of this fork and then tried to do the pull request.. From what I read, maybe I should have created a branch dedicated to this bug from the master brank of the fork.. I think i will use github desktop next time, it seems easy to use.
Anyway, I was unable to find a way to do the rebase and squash by doing it this way, so maybe that's why it failed.
Could you tell me if it is enough to merge the bug fix to the depository or if i have to follow different steps ?
Thank you and happy christmas :)

**Comment by mogikanin** [comment]
Hi Hugo, thanks for the pull request! It was simple conflict in readme file. I resolved it already. Please check my question about IProjExtensions. 
P.S. rebase\suash quite simple operations (at least in [tortoise git](http://stackoverflow.com/questions/12528854/how-to-perform-rebase-squash-using-tortoisegit)). But you can don't care about them, I'll do them by myself.

**Comment by ldrvl31** [comment]
Hi Max, thank you for resolving the conflict. I can't find your question about IProjExtensions. Could you tell me where it is please ? 
I was thinking about it and I think there can be nearly no changes in IProjExtensions if I just change ImageRectangle when ExtendBuffer is true (and adapt it where it is already used). It will be a bit simpler and cleaner, I will test this and make another pull request.

Best regards

**Comment by mogikanin** [comment]
my comment should be visible at https://github.com/DotSpatial/DotSpatial/pull/907 or here
https://github.com/DotSpatial/DotSpatial/pull/907/files/5f384181bf3e8661fdf2e82b0497ed094be5586e#diff-d6fed029636ab1ac818872886a4a4418

**Comment by ldrvl31** [comment]
Hi Max, I committed the change I was telling you about, so that IProjExtensions is barely changed compared to the previous version. I did not make another pull request but apparently it was taken into account (although it failed like the previous one). I could not see your comment in the link you gave me, I don't know why. Tell me here if you have a question about IProjExtensions !

**Comment by mogikanin** [comment]
I talked about hard-coded typename inside IProjExtensions `self.GetType().FullName.Equals("DotSpatial.Controls.MapFrame")`
But as I see you already deleted it?

**Comment by ldrvl31** [comment]
Yes i deleted it, it was simpler to change the ImageRectangle for MapFrame with ExtendBuffer instead.

What is the next step after creating the pull request ? Is it merged then tested ?

**Comment by mogikanin** [comment]
I think you already tested it? I just merge it into master. Thanks for the pull request!

**Comment by ldrvl31** [comment]
Thanks for the merge ! Yes I tested it.
As I told you earlier, I am working on the map rotation since we need it for my company software, I have seen that there is a enhancement opened (Map Rotation #658) for this so I'll probably try to make a pull request about this in a few weeks !
