### ISSUE TITLE
Exception when calling feature.Intersects(otherFeature)

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#746]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63595)**

**[ModernaTider](http://www.codeplex.com/site/users/view/ModernaTider)** wrote 2015-08-22 at 13:38
An exception occurs when checking whether two line features intersects or overlap.

Attached is Nunit test code to reproduce the problem. 

The cause of the problem has to do with feature1, for which the two first vertices are almost identical.

The problem does not occur if the z-coordinates are removed or if the first coordinate of feature 1 is removed.

**Comment by jany-tenaj** [comment]
This error occurs because we changed Coordinate.Equals to check whether z equals if the coordinates have z values.

The original implementation in GeoAPI expects Equals to be a 2d operation. Then the error does not show up, because one of the 2 coordinates with the duplicate x,y values get removed before the routine that throws the error gets run.

I think we'll revert the Coordinate.Equals to the original GeoAPI implementation and check where Equals was used with 3D intend in DotSpatial and change these calls to Equals3D.

**Comment by mogikanin** [comment]
Yes, this will work.

**Comment by jany-tenaj** [comment]
This problem is fixed as soon as we release the changed GeoAPI.
