### ISSUE TITLE
How to find the code of GeoAPI and NetTopologySuite

### ISSUE THREAD

**Issue by orbitzhan** [DotSpatial/DotSpatial#786]
Can you tell me how to find the code of GeoAPI and NetTopologySuite?
I see the new Trunk doesn't include Topology. Can you tell me the changes?
I test the Intersect method using two polygon layers, but it takes a lot time, compared with ArcGIS and QGIS.
Is any more efficient method to use? Is it possible to use QGIS instead?
Thank you!

**Comment by jany-tenaj** [comment]
You can find the code for the GeoAPI and NetTopologySuite we use [here](https://github.com/DotSpatial).

DotSpatial was updated to the newest GeoAPI and NetTopologySuite. Topology was a copy of an earlier version.
Most changes are switching from using Topology to GeoAPI and NetTopologySuite.
For geometric operations you have to use Feature.Geometry instead of Feature.
Most other changes result from name changes. For example WkbReader is now written WKBReader.
Some classes have moved to other folders because that was done in the original GeoAPI and NetTopologySuite.

**Comment by mogikanin** [comment]
@orbitzhan can we close this question?
