### ISSUE TITLE
Add FixQuality for Trimble Sentences

### ISSUE THREAD

**Issue by gojanpaolo** [DotSpatial/DotSpatial#876]
Trimble Sentences such as [PTNL,GGK ](http://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_PTNL_GGK.html)have more fix quality than what is currently available in the FixQuality enumeration.

below is the list of FixQuality to add:
1. SatelliteBasedAugmentationSystem
2. Network3DFloatRealTimeKinematic
3. Network3DFixedRealTimeKinematic
4. Network2DFloatRealTimeKinematic
5. Network2DFixedRealTimeKinematic
6. HPXPOmniStar
7. VbsOmniStar
8. LocationRealTimeKinematic
9. BeaconDifferentialGpsFix

**Comment by mogikanin** [comment]
Yes, we can add them. Do you want to provide pull request?
And for parsing Trimble sentences you are using own inheritor of `GpggkSentence`, or? Did you see this [discussion](http://dotspatial.codeplex.com/discussions/655180)?

**Comment by southburg** [comment]
Hello mogikanin,

Does providing pull request means I change the code? If yes then ok I will. 

I read [this](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md) and it says I need to wait for the issue to be tagged.

Also, I am gojanpaolo. I decided to use my own parser for the meantime since the NmeaReader class have some conflicts with the requirements of my project.

**Comment by mogikanin** [comment]
Ah, ok :) Sure, go ahead.

**Comment by gojanpaolo** [comment]
I have made a fork, branch then committed my changes but when I try to pull request, it says
"Sync failed to push local changes. It seems you do not have permission to push your changes to this repository"

**Comment by mogikanin** [comment]
Make sure that you are pushing changes into your fork, not into main repository.
