### ISSUE TITLE
Questions on 2.0

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#944]
In version 2.0, there will be a large number of breaking changes. For example, the area for a polygon feature is obtained with feature.Area() in 1.9, but will be feature.Geometry.Area in version 2.0. Is this correct?

In current 2.0, where are you supposed to put tests on toplogy-operations, for example buffering? Or is the idea that all these are no longer a DotSpatial concern but NTSTopolgy?

**Comment by jany-tenaj** [comment]
You can get the area with feature.Geometry.Area in 1.9, too. 

Feature inherits from Geometry in 1.9 but contains Geometry, too. This causes all things that work for Feature.Geometry to work for Feature, too. 
Because it is cleaner to not have everything twice and because there was something inside Geometry that didn't allow us to inherit Feature from Geometry in 2.0, Feature no longer inherits from Geometry, but just contains it.

We removed all topology tests considering them a problem of NTS. If we find that it makes sense to write tests for DotSpatial.NTS or DotSpatial.GeoAPI there is no reason why we couldn't create test projects for them.

**Comment by pedwik** [comment]
There is no feature.Geometry in 1.9, and if you mean feature.BasicGeometryit has no Area property either.

From FeatureExt:
        public static double Area(this IFeature self)
        {
            return Geometry.FromBasicGeometry(self.BasicGeometry).Area;
        }

**Comment by jany-tenaj** [comment]
Yes you're right, I meant BasicGeometry. Unfortunately I seem to have forgotten how horrible this thing was.

So you're right. IBasicGeometry unfortunately doesn't expose Area. But the underlying Class (Polygon, Point, LineString) still contains it.

Unfortunately someone went and split parts from the original IGeometry interface off and put them into IBasicGeometry and used this instead of IGeometry itself. 

That's why you have to do `Geometry.FromBasicGeometry(self.BasicGeometry).Area;` instead of `Feature.Geometry.Area` in 1.9.

Then I fear calling `Geometry.FromBasicGeometry(self.BasicGeometry).Area;` and other Geometry functions became to much code and they went and added everything to Feature so they could use less code with `Feature.Area`.

**Comment by pedwik** [comment]
I agree it will be much cleaner in DS 2.0, but users must be notified that code written for 1.9 will not work out of the box.

**Comment by jany-tenaj** [comment]
@pedwik I added the suggested hint to the changelog. 

Please close the issue if you don't have any more questions.
