### ISSUE TITLE
Roadmap v2.0?

### ISSUE THREAD

**Issue by jfevia** [DotSpatial/DotSpatial#959]
Posting here since I cannot find this information in either CodePlex or Github. 

What is the current roadmap for version 2.0? 

Changelog says there will be breaking changes. What features/changes are planned?

**Comment by mogikanin** [comment]
Everything you see in changelog will be included into 2.0. Also you can see remaining tasks here - https://github.com/DotSpatial/DotSpatial/milestone/1
I think we are almost at the finish line, and will release 2.0 soon. Breaking changes you mentioned are switching to NTS assemblies instead of DotSpatial.Topology, and changing some public interfaces. But all of these things not related to `Positioning` assemblies, there were just bug fixing.
