### ISSUE TITLE
I don't use toolbox

### ISSUE THREAD

**Issue by masgeomatik** [DotSpatial/DotSpatial#960]
Hi everyone. I'm using master version, But I dont see  toolbox.
![as00](https://cloud.githubusercontent.com/assets/26778438/24578056/4f55cf82-16e1-11e7-88c0-bab0254faa36.PNG)
 What can I do?

**Comment by jany-tenaj** [comment]
If you got your DotSpatial dlls from nuget, go and download [the latest available build from master branch](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master), because there is no nuget release for the ToolManager.

Make sure you copy the Tools folder and the Plugins\DotSpatial.Plugins.ToolManager folder from the downloaded zip into the folder where your program is run.

Your folder structure should look like inside the downloaded zip, if DemoMap.exe where your program.

- your folder
  - Tools
  - Plugins
    - DotSpatial.Plugins.ToolManager
  - YourProgram.exe

Then the toolbox is automatically added to your program, if your MainForm contains the [following code](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DemoMap/MainForm.cs).

**Comment by masgeomatik** [comment]
Thank you for help me.
I was download Relase.rar. I create new project for trying. But I'm failed :(
![as04](https://cloud.githubusercontent.com/assets/26778438/24580174/2bd7c4c2-170c-11e7-8d26-05005864529f.PNG)
Is there something wrong with me?

**Comment by masgeomatik** [comment]
Please help me :(

**Comment by jany-tenaj** [comment]
I've just seen that you have a button below your legend. Did you build your whole design yourself or just add the button?

**Comment by masgeomatik** [comment]
I use dock properties
