### ISSUE TITLE
IHeader Extension

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#991]
Hi,

I am getting this error when i try to run my application at start screen
Header Control extension must be included because UI Plugin was found

Please suggest what is the ways to resolve this issue.

Regards,
Amit

**Comment by jany-tenaj** [comment]
You need to have a single HeaderControl in your program for ui plugins to work, otherwise ui plugins can't be shown in your program.

Check out chapter 1.10.1 GDAL (Add GDAL Extension) from the [Developer getting started Guide](http://download-codeplex.sec.s-msft.com/Download?ProjectName=dotspatial&DownloadId=1460427). It explains what you have to do to add the SpatialHeaderControl and other things needed for plugins to work correctly.

**Comment by sindizzy** [comment]
I am very interested to add the GDAL extension but I do not want all the other items like the SpatialStatusStrip. I have a Windows Form where I have a custom menu and build the map and legend manually. Last time I tried I was not able to use the GDAL extensions without loading the default map, legend, dock, menu, etc.

**Comment by amitnkukanur** [comment]
What you suggested did not work, i handled that exception using try catch block.
